views/accounting.py
from flask import *
from flask_mail import *
from APIs import AccountingForms
from  APIs import AccountingAPI
import pdfkit
import datetime
import app

mod = Blueprint('accounting', __name__, url_prefix = '/accounting')

@mod.route('/')
def accounting():
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    return render_template('accounting/accounting.html', username = session['username'], data = data, bdgts = bdgts)

@mod.route('/add_category/<category>', methods = ['GET','POST'])
def add_category(category):
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    form = AccountingForms.CategoryForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                AccountingAPI.AddCategory(session['username'], session['password'],
                category,
                request.form['CategoryName'],
                request.form['CategoryDescription'])
                flash('category created successfully...', category = 'success')
                return redirect(url_for('accounting.add_category', category = category))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('accounting.add_category', category = category))
    return render_template('accounting/add-category.html', username = session['username'], data = data, category = category, form = form, bdgts = bdgts)

@mod.route('/edit_category/<category>/<account>', methods = ['GET','POST'])
def edit_category(category, account):
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    form = AccountingForms.Accounts(request.form)
    cats = AccountingAPI.GetCategory(session['username'], session['password'], account)
    AllAccounts = AccountingAPI.GetAccounts(category, account)
    form.Currency.choices = AccountingAPI.GetCurrencies()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                AccountingAPI.EditCategory(session['username'], session['password'],
                cats[0],
                request.form['CategoryName'],
                request.form['CategoryDescription'])
                return redirect(url_for('accounting.add_account', category = category, account = account))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('accounting.add_account', category = category, account = account))
    return render_template('accounting/add-account.html', username = session['username'], data = data, category = category, bdgts = bdgts, cats = cats, form = form, accounts = AllAccounts, account = account)

@mod.route('/add_account/<category>/<account>', methods = ['GET','POST'])
def add_account(category, account):
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    form = AccountingForms.Accounts(request.form)
    cats = AccountingAPI.GetCategory(session['username'], session['password'], account)
    AllAccounts = AccountingAPI.GetAccounts(category, account)
    form.Currency.choices = AccountingAPI.GetCurrencies()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                AccountingAPI.AddNewAccount(session['username'], session['password'],
                category, account, 
                request.form['AccountCode'],
                request.form['AccountName'],
                request.form['Currency'],
                request.form['OpeningBalance'],
                request.form['CurrentBalance'],
                request.form['Comments'])
                flash('Account Created', category = 'success')
                return redirect(url_for('accounting.add_account', category = category, account = account))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('accounting.add_account', category = category, account = account))
    return render_template('accounting/add-account.html', username = session['username'], data = data, category = category, bdgts = bdgts, cats = cats, form = form, accounts = AllAccounts, account = account)

templates/accounting/accounting.html
{% extends 'layout.html'%}
{% block content%}
<div class="vertical-menu">
  <h3>Accounting</h3>
 <ul class = 'warehouse' id = 'assets'><a href = "#">Assets</a>
    {% for ast in data['Assets'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Assets', account = ast)}}" id = 'toggler'>- {{ast}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Assets')}}">+ Add new Assets Category</a></li>
  </ul>
 <ul class = 'warehouse' id = 'equities'><a href = "#">Equities</a>
    {% for eqt in data['Equities'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Equities', account = eqt)}}" id = 'toggler'>- {{eqt}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Equities')}}">+ Add new Equities Category</a></li>
  </ul>
  <ul class = 'warehouse' id = 'liabilities'><a href = "#">Liabilities</a>
    {% for lbt in data['Liabilities'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Liabilities', account = lbt)}}" id = 'toggler'>- {{lbt}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Liabilities')}}">+ Add new Liabilities Category</a></li>
  </ul>
  <ul class = 'warehouse' id = 'revenues'><a href = "#">Revenues</a>
    {% for rvn in data['Revenues'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Revenues', account = rvn)}}" id = 'toggler'>- {{rvn}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Revenues')}}">+ Add new Revenues Category</a></li>
  </ul>
  <ul class = 'warehouse' id = 'expenses'><a href = "#">Expenses</a>
    {% for exp in data['Expenses'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Expenses', account = exp)}}" id = 'toggler'>- {{exp}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Expenses')}}">+ Add new Expenses Category</a></li>
  </ul>
  <ul class = 'warehouse' id = 'dividends'><a href = "#">Dividends</a>
    {% for dvd in data['Dividends'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Dividends', account = dvd)}}" id = 'toggler'>- {{dvd}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Dividends')}}">+ Add new Dividends Category</a></li>
  </ul>
  <ul class = 'warehouse' id = 'cash-check'><a href = "#">Cash Checking</a>
    {% for csh in data['Cash_Check'] %}
     <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_account', category = 'Checking_Account', account = csh)}}" id = 'toggler'>- {{csh}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "{{url_for('accounting.add_category', category = 'Checking_Account')}}">+ Add new Cash Checking Category</a></li>
  </ul>

  <a href = "#">Journal</a>
 
  <ul class = 'warehouse' id = 'budget'><a href = "#">Budget</a>
    {% for bdg in bdgts %}
     <li class = 'warehousecontent'><a href = "#" id = 'toggler'>- {{bdg}}</a></li>
    {% endfor %}
    <li class = 'warehousecontent'><a href = "#">+ Create New Budget</a></li>
  </ul>

 <ul class = 'reports' id = 'statements'><a href = "#">Statements</a>
  <li class = 'warehousecontent'><a href = "#">Balance Sheet</a></li>
  <li class = 'warehousecontent'><a href = "#">Trial Sheet</a></li>
  <li class = 'warehousecontent'><a href = "#">Net Income Statement</a></li>
  <li class = 'warehousecontent'><a href = "#">Comprehensive Income Statement</a></li>
 </ul>
 </div>
{% block accountingpage%}
{% endblock %}
{% endblock %}

templates/accounting/add-account.html
{% extends 'accounting/accounting.html'%}
{% from 'renderfield.html' import render_field %}
{% block accountingpage%}
<div class = 'actionpage'> 
    <form method = 'POST' action = "{{url_for('accounting.add_account', category = category, account = account)}}">
        <h3>Add {{account}} Account</h3>
        <div class = 'fields'>
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class = 'row'>
                <div class = 'col-a'>
                    <a href = '#' style = "text-decoration: none; font-weight: bold; padding-bottom: 20px;" class = 'edit_category'>Edit Category</a>
                </div>
            </div><br>
            {{ render_field(form.AccountCode) }}
            {{ render_field(form.AccountName) }}
            {{ render_field(form.Currency) }}
            {{ render_field(form.OpeningBalance) }}
            {{ render_field(form.CurrentBalance) }}
            {{ render_field(form.Comments) }}
        </div>
        <div class = 'submission'>
            <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class = "{{category}}">
                <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
    </form>

<table>
    <tr>
        <th>Account Code:</th>
        <th>Account Name:</th>
        <th>Currency:</th>
        <th>Open Balance:</th>
        <th>Current Balance:</th>
        <th>Edit:</th>
        <th>View Ledger:</th>
    </tr>
    {% for acc in accounts %}
        <tr>
            <td>{{acc[0]}}</td>
            <td>{{acc[1]}}</td>
            <td>{{acc[2]}}</td>
            <td>{{acc[3]}}</td>
            <td>{{acc[4]}}</td>
            <td><a href = "#"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = 'height: 25px; width: 25px;'/></a></td>
            <td><a href = "#"><img src = "{{url_for('static', filename = 'images/T.png')}}" style = 'height: 25px; width: 25px;'/></a></td>
        </tr>
    {% endfor%}
</table>

<div id="myModal" class="modal">
        <div class="modal-content">
          
          <form method = 'POST' action = "{{url_for('accounting.edit_category', category = category, account = account)}}">
                <h3>Edit {{category}} category <span class="close">&times;</span></h3>
                <div class = 'fields'>
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                    <div class = 'row'>
                        <div class = 'col-a'>
                            <label>Category Name:</label>
                        </div>
                        <div class = 'col-b'>
                            <input type = 'text' name = 'CategoryName' value = '{{cats[1]}}'/>
                        </div>
                    </div>
                    <div class = 'row'>
                        <div class = 'col-a'>
                            <label>Comments:</label>
                        </div>
                        <div class = 'col-b'>
                            <textarea name='CategoryDescription'>{{cats[2]}}</textarea>
                        </div>
                    </div>
                </div>
                <div class = 'submission'>
                    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
                </div>
            </form>
        </div>
        </div>
</div>
<script>
$(document).ready(function(){
    $('.edit_category').click(function(){
      $('#myModal').show();
    });
  
    $('.close').click(function(){
      $('#myModal').hide();
    });
  });
</script>
{% endblock %}

templates/accounting/add-category.html
{% extends 'accounting/accounting.html'%}
{% from 'renderfield.html' import render_field %}
{% block accountingpage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Add {{category}} category</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.CategoryName) }}
    {{ render_field(form.CategoryDescription) }}
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
</div>
{% endblock %}