views/logistics.py
from flask import *
from flask_mail import *
from APIs import EnterForms
from  APIs import EnterpriseAPI
import pdfkit
import datetime
import app

mod = Blueprint('logistics', __name__, url_prefix = '/logistics')

# ........ Logistics Group.
# ........ This group of applications addresses the basic working needs of...
# ........ logistics team in a company or institution. This group of urls ...
# ........ allows users to control, create and edit providers, items, ...
# ........ items gropus, packages, warehouses and their contents, ...
# ........ record all warehouse inbound and outbound transactions, ...
# ........ keeping inventory and producing required reports.
@mod.route('/')
def logistics():
    wh = EnterpriseAPI.GetWareHouses()
    return render_template('logistics/logistics.html', username = session['username'], wh = wh)

@mod.route('/Providers/', methods = ['GET' ,'POST'])
def Providers():
    form = EnterForms.ProvidersForm(request.form)
    data = EnterpriseAPI.GetProviders()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.CreateProvider(session['username'], session['password'],
                request.form['name'],
                request.form['address'],
                request.form['phone1'],
                request.form['phone2'],
                request.form['email'],
                request.form['pobox'],
                request.form['description'])
                flash('Provider added Successfully', category = 'success')
                return redirect(url_for('logistics.Providers'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.Providers'))
    return render_template('logistics/providers.html', username = session['username'], form = form, data = data, wh = wh)

@mod.route('/edit_provider/<prv>/', methods = ['GET', 'POST'])
def edit_provider(prv):
    wh = EnterpriseAPI.GetWareHouses()
    form = EnterForms.ProvidersForm(request.form)
    data = EnterpriseAPI.GetProviders()
    data1 = EnterpriseAPI.FetchProvider(session['username'], session['password'],prv)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.UpdateProvider(session['username'], session['password'], prv,
                request.form['name'],
                request.form['address'],
                request.form['phone1'],
                request.form['phone2'],
                request.form['email'],
                request.form['pobox'],
                request.form['description'])
                flash('Provider updated successfully', category = 'success')
                return redirect(url_for('logistics.Providers'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.Providers'))
    return render_template('logistics/edit_provider.html', username = session['username'], form = form, data = data, data1 = data1, wh = wh)

@mod.route('/groups/', methods = ['GET','POST'])
def groups():
    data = EnterpriseAPI.GroupList()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.AddGroup(session['username'], session['password'],
                request.form['Name'],
                request.form['description'])
                flash('Group added successfully', category = 'success')
                return redirect(url_for('logistics.groups'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.groups'))
    return render_template('logistics/groups.html', username = session['username'], data = data, wh = wh)

@mod.route('/edit_group/<id>/', methods = ['GET','POST'])
def edit_group(id):
    data = EnterpriseAPI.GetGroup(id)
    data1 = EnterpriseAPI.GroupList()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdateGroup(session['username'], session['password'], id,
                request.form['Name'],
                request.form['description'])
                flash('Group Updated Successfully', category = 'success')
                return redirect(url_for('logistics.groups'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.groups'))
    return render_template('logistics/edit_group.html', data = data, data1 = data1, username = session['username'], wh = wh)

@mod.route('/items/', methods = ['GET','POST'])
def items():
    form = EnterForms.ItemsForm(request.form)
    data = EnterpriseAPI.GetItems()
    wh = EnterpriseAPI.GetWareHouses()
    form.Group.choices = EnterpriseAPI.Groups()
    form.Provider.choices = EnterpriseAPI.ProvidersList()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.CreateItem(session['username'], session['password'],
                request.form['ItemName'],
                request.form['Brand'],
                request.form['Provider'],
                request.form['Unit'],
                request.form['UnitPrice'],
                request.form['Description'],
                request.form['Size'],
                request.form['Color'],
                request.form['SKU'],
                request.form['PartNumber'],
                request.form['IEME'],
                request.form['Length'],
                request.form['Width'],
                request.form['Height'],
                request.form['Diameter'],
                request.form['LengthUnit'],
                request.form['WidthUnit'],
                request.form['HeightUnit'],
                request.form['DiamaterUnit'],
                request.form['Group'],
                request.form['Category'])
                flash('Item added successfully', category = 'success')
                return redirect(url_for('logistics.items'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.items'))
    return render_template('logistics/items.html', username = session['username'], form = form, data = data, wh = wh)

@mod.route('/edit_item/<itm>/', methods = ['GET','POST'])
def edit_item(itm):
    data = EnterpriseAPI.GetItems()
    data1 = EnterpriseAPI.FetchItem(itm)
    provs = EnterpriseAPI.ProvidersList()
    grp = EnterpriseAPI.Groups()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdateItem(session['username'], session['password'], itm,
                request.form['ItemName'],
                request.form['Brand'],
                request.form['Provider'],
                request.form['Unit'],
                request.form['UnitPrice'],
                request.form['Description'],
                request.form['Size'],
                request.form['Color'],
                request.form['SKU'],
                request.form['PartNumber'],
                request.form['IEME'],
                request.form['Length'],
                request.form['Width'],
                request.form['Height'],
                request.form['Diameter'],
                request.form['LengthUnit'],
                request.form['WidthUnit'],
                request.form['HeightUnit'],
                request.form['DiamaterUnit'],
                request.form['Group'],
                request.form['Category'])
                flash('Item updated successfully', category = 'success')
                return redirect(url_for('logistics.items'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.items'))
    return render_template('logistics/edit_item.html', username = session['username'], data = data, data1 = data1, provs = provs, grp = grp, wh = wh)

@mod.route('/packages/', methods = ['GET','POST'])
def packages():
    itms = EnterpriseAPI.ItemPicker()
    pkg = EnterpriseAPI.GetPackages()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.CreatePackage(session['username'], session['password'],
                request.form['packagename'],
                request.form.getlist('code'),
                request.form.getlist('Name'),
                request.form.getlist('unit'),
                request.form.getlist('quantity'),
                request.form['description'])
                flash('Package Created Successcully', category = 'success')
                return redirect(url_for('logistics.packages'))
            except Exception as e:
                i = str(request.form.getlist('unit'))
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.packages'))

    return render_template('logistics/packages.html', username = session['username'], itms = itms, pkg = pkg, wh = wh)

@mod.route('/edit_package/<pkg>/', methods = ['GET','POST'])
def edit_package(pkg):
    pks, itms = EnterpriseAPI.FetchPackage(pkg)
    pkk = EnterpriseAPI.GetPackages()
    itt = EnterpriseAPI.ItemPicker()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdatePackage(session['username'], session['password'], pkg,
                request.form['packagename'],
                request.form.getlist('code'),
                request.form.getlist('Name'),

templates/logistics/add_bin.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Add Bin</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.name) }}
    {{ render_field(form.code) }}
    {{ render_field(form.status)}}
    {{ render_field(form.description)}}
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
</div>
{% endblock %}

templates/logistics/bins-report.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Bins statuses report</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class = 'row'>
        <div class = 'col-a'>
            <label>File type:</label>
        </div>
        <div class = 'col-b'>
            <select name = 'file-type'>
                <option value = 'csv'>.csv</option>
                <option value = 'pdf'>.pdf</option>
            </select>
        </div>
    </div>
    <div class = 'row'>
        <table>
            <tr>
                <th><input type = 'checkbox' id = 'select_all'/> Select all:</th>
                <th>Warehouse code:</th>
                <th>Warehouse Name:</th>
            </tr>
            {% for w in wh%}
            <tr>
                <td><input class = 'wh-check' type = 'checkbox' name = 'wh_check' value = '{{w[0]}}'/></td>
                <td>{{w[0]}}</td>
                <td>{{w[1]}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
</div>

<script>
$(document).ready(function(){
    $('#select_all').click(function(){
        $('.wh-check').prop('checked', this.checked);
    });
});
</script>
{% endblock %}

templates/logistics/bins_report.html
<html>
    <head>
        <style>
            body{font-family: "Arial Black", Gadget, sans-serif;}

            p{white-space: pre-wrap;}

            h1{
                color: white;
                background-color: rgb(0,0,100);}
                
            table{
                width: 95%;
                border: solid;
                border-width: 1px;
                border-color: #eee;
                margin-bottom: 25px;
                font-size: 10px; }

            th{
                width: auto;
                background-color: rgb(0,0,100);
                color: white;
                text-align: left;
                padding: 5px;
                border-bottom: solid;}

            tr{
                border-bottom: solid;
                border-width: 1px;
                border-color: black;
                background-color: white;}

            tr:nth-child(even){background-color: #eee;}
        </style>
    </head>
    <body>
        <h1>Enterprise Bins statuses Report</h1>
        <table>
            <tr>
                <td>Report Date:</td>
                <td>{{reportdate}}</td>
            </tr>
        </table>
        <table>
            <tr>
                <th>Warehouse:</th>
                <th>Bin:</th>
                <th>Status:</th>
                <th>Item Code:</th>
                <th>Item Name:</th>
                <th>Unit:</th>
                <th>Quantity:</th>
            </tr>
            {% for d in data%}
            <tr>
                <td>{{d[0]}}</td>
                <td>{{d[1]}}</td>
                <td>{{d[2]}}</td>
                <td>{{d[3]}}</td>
                <td>{{d[4]}}</td>
                <td>{{d[5]}}</td>
                <td>{{d[6]}}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

templates/logistics/create_warehouse.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Create Warehouse</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.Name) }}
    {{ render_field(form.Code) }}
    {{ render_field(form.Location)}}
    {{ render_field(form.Description)}}
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
</div>
{% endblock %}

templates/logistics/edit-transaction.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Edit Transactino</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class = 'row'>
        <div class = 'col-a'>
            <label>Transaciton ID:</label>
        </div>
        <div class = 'col-b'>
            <input type = 'text' name = 'transaction-id' value = '{{head[3]}}'disabled/>        
        </div>
    </div>
    <div class = 'row'>
      <div class = 'col-a'>
        <label>Transaciton Type:</label>
      </div>
      <div class = 'col-b'>
        <select name = 'transaction-type' disabled>
            <option value = '{{head[0]}}' selected hidden>{{head[0]}}</option>
            <option value = 'Inbound'>Inbound</option>
            <option value = 'Outbound'>Outbound</option>
        </select>
      </div>
    </div>
    <div class = 'row'>
        <div class = 'col-a'>
          <label>Transaciton Status:</label>
        </div>
        <div class = 'col-b'>
          <select name = 'transaction-status' id = 'statuses'>
              <option value = '{{head[2]}}' selected hidden>{{head[2]}}</option>
              <option value = 'Complete'>Complete</option>
              <option value = 'Pending'>Pending</option>
              <option value = 'Canceled'>Canceled</option>
          </select>
        </div>
      </div>
  </div>
  <div class = 'row'>
    <div class = 'col-a'>
      <label>Warehouse:</label>
    </div>
    <div class = 'col-b'>
      <select name = 'warehouse' id = 'Warehouse' disabled>
        <option value = ''>-----</option>
        <option value = '{{head[1]}}' selected hidden>{{head[1]}}</option>
        {% for w in warehouse%}
          <option value = '{{w[0]}}'>{{w[0]}}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class = 'row'>
    <div class = 'col-a'>
      <label>Refernces:</label>
    </div>
    <div class = 'col-b'>
        <select name = 'references' disabled>
          <option value = '{{head[5]}}'>{{head[5]}}</option>
          <option value = 'WH_Internal'>Warehouse internal request</option>
          {% for r in rqst%}
          <option value = '{{r[0]}}'>{{r[0]}}</option>
          {% endfor %}
        </select>
    </div>
  </div>
  <div class = 'row'>
      <div class = 'col-a'>
        <label>Comments:</label>
      </div>
      <div class = 'col-b'>
          <textarea name="comments" id = 'comments'>{{head[4]}}</textarea>
      </div>
    </div>
  <br />  
  <div class = 'itms' style = 'text-align: left;'>
    <br />
    
    <table id = 'itm-table' style = 'width: 100%;'>
      <tr>
        <th>Code:</th>
        <th>Name:</th>
        <th>Unit:</th>
        <th>Bin:</th>
        <th>Quantity:</th>
      </tr>
      {% for dt in details%}
        <tr>
            <td>{{dt[0]}}</td>
            <td>{{dt[1]}}</td>
            <td>{{dt[3]}}</td>
            <td>{{dt[2]}}</td>
            <td>{{dt[4]}}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
    <th>ID:</th>
    <th>Warehosue:</th>
    <th>Type:</th>
    <th>Creation Date:</th>
    <th>Created By:</th>
    <th>Last update:</th>
    <th>Updated By:</th>
    <th>Status:</th>
    <th>Edit:</th>
    <th>Invoice:</th>
  </tr>
  {% for tr in trans %}
   <tr class = '{{tr[6]}}'>
     <td>{{tr[7]}}</td>
     <td>{{tr[5]}}</td>
     <td>{{tr[4]}}</td>
     <td>{{tr[0]}}</td>
     <td>{{tr[1]}}</td>
     <td>{{tr[2]}}</td>
     <td>{{tr[3]}}</td>
     <td>{{tr[6]}}</td>
     <td><a href = "{{url_for('logistics.edit_transaction', transid = tr[7])}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
     <td><a href = "{{url_for('logistics.print_invoice', transid = tr[7], transby = tr[1], transtype = tr[4], transtatus = tr[6], wh = tr[5])}}"><img src = "{{url_for('static', filename = 'images/invoice.png')}}" style = "width: 25px; height: 25px;"/></a></td>
   </tr>
  {% endfor %}
 </table>
</div>
<script>
$(document).ready(function(){
    if($('#statuses option:selected').text() != "Pending"){
        $('#statuses').prop('disabled', true);
        $('#comments').prop('disabled', true);
    }
});
</script>

{% endblock %}

templates/logistics/edit_package.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Edit Package</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class = 'row'>
      <div class = 'col-a'>
        <label>Package Code:</label>
      </div>
      <div class = 'col-b'>
        <input type = 'text' name = 'packagecode' value = '{{pks[0]}}' disabled/>
      </div>
    </div>
    <div class = 'row'>
      <div class = 'col-a'>
        <label>Package Name:</label>
      </div>
      <div class = 'col-b'>
        <input type = 'text' name = 'packagename' value = '{{pks[1]}}' />
      </div>
    </div>
    <div class = 'row'>
      <div class = 'col-a'>
        <label>Description:</label>
      </div>
      <div class = 'col-b'>
        <textarea name='description'>{{pks[2]}}</textarea>
      </div>
    </div>

  </div>
  <div class = 'itms' style = 'text-align: left;'>
    <a href = '#' id = 'PickItem'>Add Item</a>
    <table id = 'itm-table'>
      <tr>
        <th>Item Code:</th>
        <th>Item Name:</th>
        <th>Unit:</th>
        <th>Quantity:</th>
        <th>Remove:</th>
      </tr>
      {% for i in itms%}
        <tr id = "{{'tr_' + i[0]}}">
          <td><input type = 'text' name = 'code' value = '{{i[0]}}' style = 'width: 100%' /></td>
          <td><input type = 'text' name = 'Name' value = '{{i[1]}}' style = 'width: 100%'/></td>
          <td><input type = 'text' name = 'unit' value = '{{i[2]}}' style = 'width: 100%' /></td>
          <td><input type = 'text' name = 'quantity' value = '{{i[3]}}' style = 'width: 100%'/></td>
          <td><a href = '#' class = 'rmv' id = '{{i[0]}}'><img src = '/static/images/rmv.png' style = 'height: 20px; width: 20px;'/></a></td>
        </tr>
      {% endfor %}

    </table>
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
    <th>Code:</th>
    <th>Name:</th>
    <th>Edit:</th>
  </tr>
  {% for p in pkk %}
  <tr>
    <td>{{p[0]}}</td>
    <td>{{p[1]}}</td>
    <td><a href = "{{url_for('logistics.edit_package', pkg = p[0])}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
  </tr>
  {% endfor %}
</table>
</div>
<div id="myModal" class="modal">
  <div class="modal-content">
    <h3>Pick Item <span class="close">&times;</span></h3>
    <h5 style = 'color: green;'> Pick an item from the table below to add it to package</h5>
    <div class = 'items' stye = 'overflow: scroll;'>
      <table>
        <tr>
          <th>Item Code:</th>
          <th>Item Name: </th>
          <th>Provider: </th>
          <th>Unit: </th>
        </tr>
        {% for t in itt %}
          <tr>
            <td><a class = 'itm' href = '#'>{{t[0]}}</a></td>
            <td>{{t[1]}}</td>
            <td>{{t[2]}}</td>
            <td>{{t[3]}}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>

<script>
  $(function(){
    var i = 0;
    $('.itm').click(function(){
      i++
      $.getJSON('/GrabItems', {
        ItCode: $(this).text(),
      }, function(data){
        if(data.msg == 'success'){
          $('#itm-table').append("<tr id = 'tr_"+i+"'><td><input type = 'text' name = 'code' value = '"+data.itemcode+"' style = 'width: 100%' /></td><td><input type = 'text' name = 'Name' value = '"+data.itemname+"' style = 'width: 100%'/></td><td><input type = 'text' name = 'unit' value = '"+data.itemunit+"' style = 'width: 100%' /></td><td><input type = 'text' name = 'quantity' style = 'width: 100%'/></td><td><a href = '#' class = 'rmv' id = '"+i+"'><img src = '/static/images/rmv.png' style = 'height: 20px; width: 20px;'/></a></td></tr>");
        }
        else{
          $('.msg').val('Item not found');
        }
      });
      $('#myModal').hide();
      return false;
    });

    $(document).on('click','.rmv', function(){
      var ids = $(this).attr('id');
      $('#tr_'+ ids).remove();
    });
  });
</script>

{% endblock %}

templates/logistics/edit_provider.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Edit Provider</h3>
  <div class = 'fields'>
    {% for i in data1 %}
    <div class = 'row'>
      <div class = 'col-a'>
        <label>ID:</label>
      </div>
      <div class = 'col-b'>
        <input type = 'text' name = 'id' value = '{{i[0]}}' disabled />
      </div>
    </div>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.name, value = i[1]) }}
    {{ render_field(form.address, value = i[2]) }}
    {{ render_field(form.phone1, value = i[3])}}
    {{ render_field(form.phone2, value = i[4])}}
    {{ render_field(form.email, value = i[5])}}
    {{ render_field(form.pobox, value = i[6])}}
    <div class = 'row'>
    <div class = 'col-a'>
      <label>Description:</label>
    </div>
    <div class = 'col-b'>
      <textarea name = 'description'>{{i[7]}}</textarea>
    </div>
    </div>
  </div>
    {% endfor %}
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
      <th>ID:</th>
      <th>Name:</th>
      <th>Address:</th>
      <th>Phone #1:</th>
      <th>Phone #2:</th>
      <th>email:</th>
      <th>PO-BOX:</th>
      <th>Edit:</th>
    </tr>
    {% for d in data %}
      <tr>
        <td>{{d[0]}}</td>
        <td>{{d[1]}}</td>
        <td>{{d[2]}}</td>
        <td>{{d[3]}}</td>
        <td>{{d[4]}}</td>
        <td>{{d[5]}}</td>
        <td>{{d[6]}}</td>
        <td><a href = "{{url_for('logistics.edit_provider', prv = d[0])}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/logistics/providers.html
{% extends 'logistics/logistics.html'%}
{% from 'renderfield.html' import render_field %}
{% block logisticspage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Create Provider</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.name) }}
    {{ render_field(form.address) }}
    {{ render_field(form.phone1)}}
    {{ render_field(form.phone2)}}
    {{ render_field(form.email)}}
    {{ render_field(form.pobox)}}
    {{ render_field(form.description)}}
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
      <th>ID:</th>
      <th>Name:</th>
      <th>Address:</th>
      <th>Phone #1:</th>
      <th>Phone #2:</th>
      <th>email:</th>
      <th>PO-BOX:</th>
      <th>Edit:</th>
    </tr>
    {% for d in data %}
      <tr>
        <td>{{d[0]}}</td>
        <td>{{d[1]}}</td>
        <td>{{d[2]}}</td>
        <td>{{d[3]}}</td>
        <td>{{d[4]}}</td>
        <td>{{d[5]}}</td>
        <td>{{d[6]}}</td>
        <td><a href = "{{url_for('logistics.edit_provider', prv = d[0])}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}