views/accounting.py
from flask import *
from flask_mail import *
from APIs import AccountingForms
from  APIs import AccountingAPI
import pdfkit
import datetime
import app

mod = Blueprint('accounting', __name__, url_prefix = '/accounting')

@mod.route('/')
def accounting():
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    return render_template('accounting/accounting.html', username = session['username'], data = data, bdgts = bdgts)

@mod.route('/add_category/<category>', methods = ['GET','POST'])
def add_category(category):
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    form = AccountingForms.CategoryForm(request.form)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                AccountingAPI.AddCategory(session['username'], session['password'],
                category,
                request.form['CategoryName'],
                request.form['CategoryDescription'])
                flash('category created successfully...', category = 'success')
                return redirect(url_for('accounting.add_category', category = category))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('accounting.add_category', category = category))
    return render_template('accounting/add-category.html', username = session['username'], data = data, category = category, form = form, bdgts = bdgts)

@mod.route('/edit_category/<category>/<account>', methods = ['GET','POST'])
def edit_category(category, account):
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    form = AccountingForms.Accounts(request.form)
    cats = AccountingAPI.GetCategory(session['username'], session['password'], account)
    AllAccounts = AccountingAPI.GetAccounts(category, account)
    form.Currency.choices = AccountingAPI.GetCurrencies()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                AccountingAPI.EditCategory(session['username'], session['password'],
                cats[0],
                request.form['CategoryName'],
                request.form['CategoryDescription'])
                return redirect(url_for('accounting.add_account', category = category, account = account))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('accounting.add_account', category = category, account = account))
    return render_template('accounting/add-account.html', username = session['username'], data = data, category = category, bdgts = bdgts, cats = cats, form = form, accounts = AllAccounts, account = account)

@mod.route('/add_account/<category>/<account>', methods = ['GET','POST'])
def add_account(category, account):
    data = AccountingAPI.GetCategories()
    bdgts = AccountingAPI.GetBudgets()
    form = AccountingForms.Accounts(request.form)
    cats = AccountingAPI.GetCategory(session['username'], session['password'], account)
    AllAccounts = AccountingAPI.GetAccounts(category, account)
    form.Currency.choices = AccountingAPI.GetCurrencies()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                AccountingAPI.AddNewAccount(session['username'], session['password'],
                category, account, 
                request.form['AccountCode'],
                request.form['AccountName'],
                request.form['Currency'],
                request.form['OpeningBalance'],
                request.form['CurrentBalance'],
                request.form['Comments'])
                flash('Account Created', category = 'success')
                return redirect(url_for('accounting.add_account', category = category, account = account))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('accounting.add_account', category = category, account = account))
    return render_template('accounting/add-account.html', username = session['username'], data = data, category = category, bdgts = bdgts, cats = cats, form = form, accounts = AllAccounts, account = account)

views/logistics.py
from flask import *
from flask_mail import *
from APIs import EnterForms
from  APIs import EnterpriseAPI
import pdfkit
import datetime
import app

mod = Blueprint('logistics', __name__, url_prefix = '/logistics')

# ........ Logistics Group.
# ........ This group of applications addresses the basic working needs of...
# ........ logistics team in a company or institution. This group of urls ...
# ........ allows users to control, create and edit providers, items, ...
# ........ items gropus, packages, warehouses and their contents, ...
# ........ record all warehouse inbound and outbound transactions, ...
# ........ keeping inventory and producing required reports.
@mod.route('/')
def logistics():
    wh = EnterpriseAPI.GetWareHouses()
    return render_template('logistics/logistics.html', username = session['username'], wh = wh)

@mod.route('/Providers/', methods = ['GET' ,'POST'])
def Providers():
    form = EnterForms.ProvidersForm(request.form)
    data = EnterpriseAPI.GetProviders()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.CreateProvider(session['username'], session['password'],
                request.form['name'],
                request.form['address'],
                request.form['phone1'],
                request.form['phone2'],
                request.form['email'],
                request.form['pobox'],
                request.form['description'])
                flash('Provider added Successfully', category = 'success')
                return redirect(url_for('logistics.Providers'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.Providers'))
    return render_template('logistics/providers.html', username = session['username'], form = form, data = data, wh = wh)

@mod.route('/edit_provider/<prv>/', methods = ['GET', 'POST'])
def edit_provider(prv):
    wh = EnterpriseAPI.GetWareHouses()
    form = EnterForms.ProvidersForm(request.form)
    data = EnterpriseAPI.GetProviders()
    data1 = EnterpriseAPI.FetchProvider(session['username'], session['password'],prv)
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.UpdateProvider(session['username'], session['password'], prv,
                request.form['name'],
                request.form['address'],
                request.form['phone1'],
                request.form['phone2'],
                request.form['email'],
                request.form['pobox'],
                request.form['description'])
                flash('Provider updated successfully', category = 'success')
                return redirect(url_for('logistics.Providers'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.Providers'))
    return render_template('logistics/edit_provider.html', username = session['username'], form = form, data = data, data1 = data1, wh = wh)

@mod.route('/groups/', methods = ['GET','POST'])
def groups():
    data = EnterpriseAPI.GroupList()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.AddGroup(session['username'], session['password'],
                request.form['Name'],
                request.form['description'])
                flash('Group added successfully', category = 'success')
                return redirect(url_for('logistics.groups'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.groups'))
    return render_template('logistics/groups.html', username = session['username'], data = data, wh = wh)

@mod.route('/edit_group/<id>/', methods = ['GET','POST'])
def edit_group(id):
    data = EnterpriseAPI.GetGroup(id)
    data1 = EnterpriseAPI.GroupList()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdateGroup(session['username'], session['password'], id,
                request.form['Name'],
                request.form['description'])
                flash('Group Updated Successfully', category = 'success')
                return redirect(url_for('logistics.groups'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.groups'))
    return render_template('logistics/edit_group.html', data = data, data1 = data1, username = session['username'], wh = wh)

@mod.route('/items/', methods = ['GET','POST'])
def items():
    form = EnterForms.ItemsForm(request.form)
    data = EnterpriseAPI.GetItems()
    wh = EnterpriseAPI.GetWareHouses()
    form.Group.choices = EnterpriseAPI.Groups()
    form.Provider.choices = EnterpriseAPI.ProvidersList()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.CreateItem(session['username'], session['password'],
                request.form['ItemName'],
                request.form['Brand'],
                request.form['Provider'],
                request.form['Unit'],
                request.form['UnitPrice'],
                request.form['Description'],
                request.form['Size'],
                request.form['Color'],
                request.form['SKU'],
                request.form['PartNumber'],
                request.form['IEME'],
                request.form['Length'],
                request.form['Width'],
                request.form['Height'],
                request.form['Diameter'],
                request.form['LengthUnit'],
                request.form['WidthUnit'],
                request.form['HeightUnit'],
                request.form['DiamaterUnit'],
                request.form['Group'],
                request.form['Category'])
                flash('Item added successfully', category = 'success')
                return redirect(url_for('logistics.items'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.items'))
    return render_template('logistics/items.html', username = session['username'], form = form, data = data, wh = wh)

@mod.route('/edit_item/<itm>/', methods = ['GET','POST'])
def edit_item(itm):
    data = EnterpriseAPI.GetItems()
    data1 = EnterpriseAPI.FetchItem(itm)
    provs = EnterpriseAPI.ProvidersList()
    grp = EnterpriseAPI.Groups()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdateItem(session['username'], session['password'], itm,
                request.form['ItemName'],
                request.form['Brand'],
                request.form['Provider'],
                request.form['Unit'],
                request.form['UnitPrice'],
                request.form['Description'],
                request.form['Size'],
                request.form['Color'],
                request.form['SKU'],
                request.form['PartNumber'],
                request.form['IEME'],
                request.form['Length'],
                request.form['Width'],
                request.form['Height'],
                request.form['Diameter'],
                request.form['LengthUnit'],
                request.form['WidthUnit'],
                request.form['HeightUnit'],
                request.form['DiamaterUnit'],
                request.form['Group'],
                request.form['Category'])
                flash('Item updated successfully', category = 'success')
                return redirect(url_for('logistics.items'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.items'))
    return render_template('logistics/edit_item.html', username = session['username'], data = data, data1 = data1, provs = provs, grp = grp, wh = wh)

@mod.route('/packages/', methods = ['GET','POST'])
def packages():
    itms = EnterpriseAPI.ItemPicker()
    pkg = EnterpriseAPI.GetPackages()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.CreatePackage(session['username'], session['password'],
                request.form['packagename'],
                request.form.getlist('code'),
                request.form.getlist('Name'),
                request.form.getlist('unit'),
                request.form.getlist('quantity'),
                request.form['description'])
                flash('Package Created Successcully', category = 'success')
                return redirect(url_for('logistics.packages'))
            except Exception as e:
                i = str(request.form.getlist('unit'))
                flash(str(e), category = 'fail')
                return redirect(url_for('logistics.packages'))

    return render_template('logistics/packages.html', username = session['username'], itms = itms, pkg = pkg, wh = wh)

@mod.route('/edit_package/<pkg>/', methods = ['GET','POST'])
def edit_package(pkg):
    pks, itms = EnterpriseAPI.FetchPackage(pkg)
    pkk = EnterpriseAPI.GetPackages()
    itt = EnterpriseAPI.ItemPicker()
    wh = EnterpriseAPI.GetWareHouses()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdatePackage(session['username'], session['password'], pkg,
                request.form['packagename'],
                request.form.getlist('code'),
                request.form.getlist('Name'),

templates/home.html
{% extends 'layout.html'%}
{% block content%}

{% endblock %}

templates/layout.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_main.css')}}"/>
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/jquery.treetable.css')}}"/>
    <link rel="icon" href="{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" />
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.min.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery-ui.min.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/PickItem.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/PickPackage.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/BinEditor.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/toggler.js')}}"></script>
  </head>
  <body>
    <nav class = "main-nav">
      <ul>
        <li><a href = "{{url_for('users.create_user')}}">Users</a></li>
        <li><a href = "{{url_for('logistics.logistics')}}">Logistics</a></li>
        <li><a href = "{{url_for('accounting.accounting')}}">Accounting</a></li>
        <li><a href = "#">Procurement</a></li>
        <li><a href = "#'">Sales</a></li>
        <li class="dropdown">
          <a href="javascript:void(0)" class="dropbtn">{{username}}</a>
          <div class="dropdown-content">
            <a href="{{url_for('profile.user_profile', user = username)}}">View Profile</a>
            <a href="{{url_for('logout')}}">Log Out</a>
          </div>
        </li>
      </ul>
    </nav>

    <div class = 'mainpage'>
    {% block content %}
    {% endblock%}
    </div>
  </body>
</html>

templates/login.html
<html>
  <head>
    <title>Enterprise</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = 'stylesheet' href = "{{url_for('static', filename = 'css/style_login.css')}}" />
    <link rel="icon" href = "{{url_for('static', filename = 'images/logo.png')}}" sizes="16x16" /> 
  </head>
  <body>
    <form method = 'POST' action = "{{url_for('login')}}">
      <div class = 'fields'>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class = 'title'>
          <h2>Enterprise</h2>
          <h5>for Finance and Logistics Management</h5>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.usrname.label}}
          </div>
          <div class = 'col-b'>
            {{form.usrname}}
          </div>
        </div>
        <div class = 'row'>
          <div class = 'col-a'>
            {{form.passwd.label}}
          </div>
          <div class = 'col-b'>
            {{form.passwd}}
          </div>
        </div>
      </div>
      <div class = 'submission'>
        <input type = 'submit' name = 'submit' class = 'btn-active' value = 'Login'/>
        <a href = '#'>Forgot Password</a>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                <div class = "{{category}}">
                <p>{{ message }}</p>
                </div>
              {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
    </form>
  </body>
</html>

templates/renderfield.html
{% macro render_field(field) %}
<div class = 'row'>
  <div class = 'col-a'>
    {{field.label}}
  </div>
  <div class = 'col-b'>
    {{field(**kwargs)|safe}}
  </div>
</div>
{% endmacro %}

templates/tester.html
<html>
  <head>
    <title>Testig Page</title>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.js')}}"></script>
    <script src = "{{url_for('static', filename = 'js/jquery/dist/jquery.min.js')}}"></script>
  </head>
  <body>
    <form>
      <div class = 'fields'>
        <input type = 'text' name = 'fuckit' />
        <a href = "#" id = 'adder'>Add Line</a>
      </div>
      <div class = 'submission'>
        <input type = 'submit' name = 'submit' value = 'Submit'/>
      </div>
    </form>
  </body>
  <script>
    $(document).ready(function(){
      var i = 1;
      $('#adder').click(function(){
        i++;
        $('.fields').append("<div class = 'added' id = 'div_"+i+"'><input type = 'text' name = 'fuckit' /><a href = '#' class = 'rmv' id = '"+i+"'>remove</a></div>");
      });

      $(document).on('click', '.rmv', function(){
        var ids = $(this).attr('id');
        $('#div_'+ ids).remove();
      });
    });
  </script>
</html>