views/users.py
from flask import *
from flask_mail import *
import app
from APIs import EnterForms
from  APIs import EnterpriseAPI


mod = Blueprint('users', __name__, url_prefix = '/users')

@mod.route('/')
def admin():
    return render_template('users/admin.html', username = session['username'])

# ........ Creating new user indivisually using the CreateUser...
# ........ API at Model.py.
@mod.route('/create_user/', methods = ['GET', 'POST'])
def create_user():
    form = EnterForms.CreateUser(request.form)
    data = EnterpriseAPI.GetUsers()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                usrname, pswd = EnterpriseAPI.CreateUser(session['username'], session['password'],
                request.form['firstname'],
                request.form['lastname'],
                request.form['company'],
                request.form['position'],
                request.form['department'],
                request.form['email'],
                request.form['phone1'],
                request.form['phone2'],
                request.form['usrtype'],
                request.form.getlist('appr-check'))
                msg = Message('New Enterprise Account', recipients = [str(request.form['email'])])
                msg.body = "Dear {}, \n Thank you for using Enterprise. please note that your username is: {} and your password is {}. \n It is highly recommended that you change your password as soon as possible. \n Thank you for using Enterprise.".format(str(request.form['firstname']), str(usrname), str(pswd)) 
                app.mail.send(msg)
                flash('User Created Successfully', category = 'success')
                return redirect(url_for('users.create_user'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return render_template('users/create_user.html', username = session['username'], data = data, form = form)
    return render_template('users/create_user.html', username = session['username'], data = data, form = form)

# ........ Resetting user password to initial default password.
@mod.route('/reset_password/<user>/')
def reset_password(user):
    try:
        NewPass, Name = EnterpriseAPI.ResetPassword(session['username'], session['password'], user)
        flash('User Password was reset', category = 'success')
        msg = Message('Enterprise password reset', recipients = [Name[2]])
        msg.body = "Dear {}, \n Please note that your password has been reset into {} . \n Please note it is highly adviised that you change your password soon. \n Thank you for using Enterprise.".format(Name[0], NewPass)
        app.mail.send(msg)
        return redirect(url_for('users.create_user'))
    except Exception as e:
        flash(str(e), category = 'fail')
        return redirect(url_for('users.create_user'))

# ........ This route utilizes CreateUser API at Model.py...
# ........ along with access to excel sheets using openpyxl library...
# ........ It allows administrators to create several users ...
# ........ in the same time in a bulk from a excel template.
# ........ It is IMPORTANT that users use our distributed ...
# ........ excel template as the API reads directly from it.
@mod.route('/create_multiple_users/', methods = ['GET', 'POST'])
def create_multiple_users():
    form = EnterForms.FileForm(request.form)
    data = EnterpriseAPI.GetUsers()
    if request.method == 'POST':
        if request.form['submit'] == 'Submit' and form.validate():
            try:
                EnterpriseAPI.CreateMultipleUsers(session['username'], session['password'], request.form['FileName'])
                flash('Multiple Users successfully created', category = 'success')
                return redirect(url_for('users.create_multiple_users'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return render_template('users/create_multiple_users.html', username = session['username'], form = form)
    return render_template('users/create_multiple_users.html', username = session['username'], form = form, data = data)

# ........ Updating user information using UpdateUser API at Model.py
# ........ This allows administrators to update users' info and assigned...
# ........ privilages.
@mod.route('/edit_user/<id>/', methods = ['GET', 'POST'])
def edit_user(id):
    data1 = EnterpriseAPI.GetUsers()
    data2 = EnterpriseAPI.GetUserInfo(id)
    data3 = EnterpriseAPI.GetApprovals(data2[0][3])
    if request.method == 'POST':
        if request.form['submit'] == 'Submit':
            try:
                EnterpriseAPI.UpdateUser(session['username'], session['password'], id,
                request.form['firstname'],
                request.form['lastname'],
                request.form['company'],
                request.form['position'],
                request.form['department'],
                request.form['email'],
                request.form['phone1'],
                request.form['phone2'],
                request.form['usertype'],
                request.form['status'],
                request.form.getlist('appr-check'), data2[0][3])
                flash('User Updated Successfully', category = 'success')
                return redirect(url_for('users.create_user'))
            except Exception as e:
                flash(str(e), category = 'fail')
                return redirect(url_for('users.create_user'))
    return render_template('users/edit_user.html', username = session['username'], data1 = data1, data2 = data2, data3 = data3)

templates/users/admin.html
{% extends 'layout.html'%}
{% block content%}
<div class="vertical-menu">
  <h3>Users</h3>
 <a href = "{{url_for('users.create_user')}}">Create/Edit Users</a>
 <a href = "{{url_for('users.create_multiple_users')}}">Create users from external template</a>
</div>

  {% block adminpage%}
  {% endblock %}

{% endblock %}

templates/users/create_multiple_users.html
{% extends 'users/admin.html'%}
{% from 'renderfield.html' import render_field %}
{% block adminpage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Create multiple users from external template</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.FileName) }}
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>UserName</th>
      <th>Company</th>
      <th>Position</th>
      <th>department</th>
      <th>Email</th>
      <th>Phone #1</th>
      <th>Phone #2</th>
      <th>User Type</th>
      <th>Status</th>
      <th>Edit</th>
      <th>Reset Password</th>
    </tr>
    {% for d in data %}
      <tr>
        <td class = '{{d[11]}}'>{{d[0]}}</td>
        <td class = '{{d[11]}}'>{{d[1]}}</td>
        <td class = '{{d[11]}}'>{{d[2]}}</td>
        <td class = '{{d[11]}}'>{{d[3]}}</td>
        <td class = '{{d[11]}}'>{{d[4]}}</td>
        <td class = '{{d[11]}}'>{{d[5]}}</td>
        <td class = '{{d[11]}}'>{{d[6]}}</td>
        <td class = '{{d[11]}}'>{{d[7]}}</td>
        <td class = '{{d[11]}}'>{{d[8]}}</td>
        <td class = '{{d[11]}}'>{{d[9]}}</td>
        <td class = '{{d[11]}}'>{{d[10]}}</td>
        <td class = '{{d[11]}}'>{{d[11]}}</td>
        <td class = '{{d[11]}}'><a href = "{{url_for('users.edit_user', id = d[0])}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
        <td class = '{{d[11]}}'><a href = "{{url_for('users.reset_password', user = d[0])}}"><img src = "{{url_for('static', filename = 'images/reset_password.png')}}" style = "width: 25px; height: 25px;"/></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/users/create_user.html
{% extends 'users/admin.html'%}
{% from 'renderfield.html' import render_field %}
{% block adminpage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Create User</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {{ render_field(form.firstname) }}
    {{ render_field(form.lastname) }}
    {{ render_field(form.company)}}
    {{ render_field(form.position)}}
    {{ render_field(form.department)}}
    {{ render_field(form.email)}}
    {{ render_field(form.phone1)}}
    {{ render_field(form.phone2)}}
    {{ render_field(form.usrtype)}}
    <h5 style = 'color: rgb(0,0,100); font-weight: bold;'>Can Approve:</h5>
    <table>
      <tr>
        <th><input type = 'Checkbox' id = 'select_all' /></th>
        <th>All</th>
      </tr>
      <tr>
        <td><input type = 'Checkbox' value = 'inventory-requests' name = 'appr-check' class = 'appr_check'/></td>
        <td>Inventory Requests</td>
      </tr>
    </table>
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>UserName</th>
      <th>Company</th>
      <th>Position</th>
      <th>department</th>
      <th>Email</th>
      <th>Phone #1</th>
      <th>Phone #2</th>
      <th>User Type</th>
      <th>Status</th>
      <th>Edit</th>
      <th>Reset Password</th>
    </tr>
    {% for d in data %}
      <tr>
        <td class = '{{d[11]}}'>{{d[0]}}</td>
        <td class = '{{d[11]}}'>{{d[1]}}</td>
        <td class = '{{d[11]}}'>{{d[2]}}</td>
        <td class = '{{d[11]}}'>{{d[3]}}</td>
        <td class = '{{d[11]}}'>{{d[4]}}</td>
        <td class = '{{d[11]}}'>{{d[5]}}</td>
        <td class = '{{d[11]}}'>{{d[6]}}</td>
        <td class = '{{d[11]}}'>{{d[7]}}</td>
        <td class = '{{d[11]}}'>{{d[8]}}</td>
        <td class = '{{d[11]}}'>{{d[9]}}</td>
        <td class = '{{d[11]}}'>{{d[10]}}</td>
        <td class = '{{d[11]}}'>{{d[11]}}</td>
        <td class = '{{d[11]}}'><a href = "{{url_for('users.edit_user', id = d[0])}}"><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
        <td class = '{{d[11]}}'><a href = "{{url_for('users.reset_password', user = d[0])}}"><img src = "{{url_for('static', filename = 'images/reset_password.png')}}" style = "width: 25px; height: 25px;"/></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
<script>
    $(document).ready(function(){
        $('#select_all').click(function(){
            $('.appr_check').prop('checked', this.checked);
        });
    });
</script>
{% endblock %}

templates/users/edit_user.html
{% extends 'users/admin.html'%}
{% from 'renderfield.html' import render_field %}
{% block adminpage%}
<div class = 'actionpage'>
<form method = 'post'>
  <h3>Edit User</h3>
  <div class = 'fields'>
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    {% for d in data2 %}
      <div class = 'row'>
        <div class = 'col-a'>
          <label>ID: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'ID' value = '{{d[0]}}' disabled />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>First name: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'firstname' value = '{{d[1]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Last Name: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'lastname' value = '{{d[2]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>User Name: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'usrname' value = '{{d[3]}}' disabled/>
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Company: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'company' value = '{{d[5]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Position: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'position' value = '{{d[6]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Department: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'department' value = '{{d[7]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Email: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'email' value = '{{d[8]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Phone #1: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'phone1' value = '{{d[9]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Phone #2: </label>
        </div>
        <div class = 'col-b'>
          <input type = 'text' name = 'phone2' value = '{{d[10]}}' />
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>User Type: </label>
        </div>
        <div class = 'col-b'>
          <select name = 'usertype'>
            <option value = '{{d[11]}}' hidden>{{d[11]}}</option>
            <option value = 'Admin'>Admin</option>
            <option value = 'Viewer'>Viewer</option>
            <option value = 'User'>User</option>
          </select>
        </div>
      </div>
      <div class = 'row'>
        <div class = 'col-a'>
          <label>Status: </label>
        </div>
        <div class = 'col-b'>
          <select name = 'status'>
            <option value = '{{d[12]}}' hidden>{{d[12]}}</option>
            <option value = 'Active'>Active</option>
            <option value = 'Inactive'>Inactive</option>
          </select>
        </div>
    </div>
    <h5 style = 'color: rgb(0,0,100); font-weight: bold;'>Can Approve:</h5>
    
    <table>
      <tr>
        <th><input type = 'Checkbox' id = 'select_all' /></th>
        <th>All</th>
      </tr>
      <tr>
        <td><input type = 'Checkbox' value = 'inventory-requests' name = 'appr-check' class = 'appr_check' {% for d in data3 %}{% if d[0] == 'inventory-requests' %} checked {% else %}{% endif %}{%endfor%}/></td>
        <td>Inventory Requests</td>
      </tr>
    </table>
    
    {% endfor %}
  </div>
  <div class = 'submission'>
    <input type = 'submit' class = 'btn-active' name = 'submit' value = 'Submit' />
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
          {% for category, message in messages %}
            <div class = "{{category}}">
            <p>{{ message }}</p>
            </div>
          {% endfor %}
      {% endif %}
    {% endwith %}
  </div>
</form>
<table>
  <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>UserName</th>
      <th>Company</th>
      <th>Position</th>
      <th>department</th>
      <th>Email</th>
      <th>Phone #1</th>
      <th>Phone #2</th>
      <th>User Type</th>
      <th>Status</th>
      <th>Edit</th>
      <th>Reset Password</th>
    </tr>
    {% for d in data1 %}
      <tr>
        <td class = '{{d[11]}}'>{{d[0]}}</td>
        <td class = '{{d[11]}}'>{{d[1]}}</td>
        <td class = '{{d[11]}}'>{{d[2]}}</td>
        <td class = '{{d[11]}}'>{{d[3]}}</td>
        <td class = '{{d[11]}}'>{{d[4]}}</td>
        <td class = '{{d[11]}}'>{{d[5]}}</td>
        <td class = '{{d[11]}}'>{{d[6]}}</td>
        <td class = '{{d[11]}}'>{{d[7]}}</td>
        <td class = '{{d[11]}}'>{{d[8]}}</td>
        <td class = '{{d[11]}}'>{{d[9]}}</td>
        <td class = '{{d[11]}}'>{{d[10]}}</td>
        <td class = '{{d[11]}}'>{{d[11]}}</td>
        <td class = '{{d[11]}}'><a href = "{{url_for('users.edit_user', id = d[0])}}""><img src = "{{url_for('static', filename = 'images/edit.png')}}" style = "width: 25px; height: 25px;"/></a></td>
        <td class = '{{d[11]}}'><a href = "{{url_for('users.reset_password', user = d[0])}}"><img src = "{{url_for('static', filename = 'images/reset_password.png')}}" style = "width: 25px; height: 25px;"/></a></td>
      </tr>
    {% endfor %}
  </table>
</div>
<script>
    $(document).ready(function(){
        $('#select_all').click(function(){
            $('.appr_check').prop('checked', this.checked);
        });
    });
</script>
{% endblock %}